[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "CombatLogic.lua"
pattern = '''
				if modifierData.PlayerMultiplier and (attacker == CurrentRun.Hero or ( attacker ~= nil and UnitSets.PlayerSummons[attacker.Name] )) then
					addDamageMultiplier( modifierData, modifierData.PlayerMultiplier )
				end
'''
position = "after"
payload = '''
if modifierData.HitArmorMultiplier and triggerArgs.HitArmor then
    addDamageMultiplier( modifierData, modifierData.HitArmorMultiplier )
end
'''
match_indent = true
times = 1
